export const wordGroups = [
  {
    id: 'animals',
    label: 'Animals',
    words: [
      { kana: 'ねこ',       romaji: ['neko'],              meaning: 'cat' },
      { kana: 'いぬ',       romaji: ['inu'],               meaning: 'dog' },
      { kana: 'さかな',     romaji: ['sakana'],            meaning: 'fish' },
      { kana: 'とり',       romaji: ['tori'],              meaning: 'bird' },
      { kana: 'うし',       romaji: ['ushi'],              meaning: 'cow' },
      { kana: 'うま',       romaji: ['uma'],               meaning: 'horse' },
      { kana: 'くま',       romaji: ['kuma'],              meaning: 'bear' },
      { kana: 'うさぎ',     romaji: ['usagi'],             meaning: 'rabbit' },
      { kana: 'かえる',     romaji: ['kaeru'],             meaning: 'frog' },
      { kana: 'へび',       romaji: ['hebi'],              meaning: 'snake' },
    ],
  },
  {
    id: 'food',
    label: 'Food & Drink',
    words: [
      { kana: 'ごはん',     romaji: ['gohan'],             meaning: 'rice / meal' },
      { kana: 'みず',       romaji: ['mizu'],              meaning: 'water' },
      { kana: 'おちゃ',     romaji: ['ocha'],              meaning: 'tea' },
      { kana: 'すし',       romaji: ['sushi', 'susi'],     meaning: 'sushi' },
      { kana: 'たまご',     romaji: ['tamago'],            meaning: 'egg' },
      { kana: 'やさい',     romaji: ['yasai'],             meaning: 'vegetables' },
      { kana: 'にく',       romaji: ['niku'],              meaning: 'meat' },
      { kana: 'パン',       romaji: ['pan'],               meaning: 'bread' },
      { kana: 'ラーメン',   romaji: ['raamen', 'ramen'],   meaning: 'ramen' },
      { kana: 'てんぷら',   romaji: ['tenpura', 'tempura'], meaning: 'tempura' },
    ],
  },
  {
    id: 'body',
    label: 'Body',
    words: [
      { kana: 'め',         romaji: ['me'],                meaning: 'eye' },
      { kana: 'みみ',       romaji: ['mimi'],              meaning: 'ear' },
      { kana: 'はな',       romaji: ['hana'],              meaning: 'nose' },
      { kana: 'くち',       romaji: ['kuchi'],             meaning: 'mouth' },
      { kana: 'て',         romaji: ['te'],                meaning: 'hand' },
      { kana: 'あし',       romaji: ['ashi'],              meaning: 'foot / leg' },
      { kana: 'あたま',     romaji: ['atama'],             meaning: 'head' },
      { kana: 'かみ',       romaji: ['kami'],              meaning: 'hair' },
      { kana: 'かお',       romaji: ['kao'],               meaning: 'face' },
      { kana: 'せなか',     romaji: ['senaka'],            meaning: 'back' },
    ],
  },
  {
    id: 'colors',
    label: 'Colors',
    words: [
      { kana: 'あか',       romaji: ['aka'],               meaning: 'red' },
      { kana: 'あお',       romaji: ['ao'],                meaning: 'blue' },
      { kana: 'しろ',       romaji: ['shiro', 'siro'],     meaning: 'white' },
      { kana: 'くろ',       romaji: ['kuro'],              meaning: 'black' },
      { kana: 'きいろ',     romaji: ['kiiro'],             meaning: 'yellow' },
      { kana: 'みどり',     romaji: ['midori'],            meaning: 'green' },
      { kana: 'むらさき',   romaji: ['murasaki'],          meaning: 'purple' },
      { kana: 'ちゃいろ',   romaji: ['chairo', 'tyairo'],  meaning: 'brown' },
      { kana: 'ピンク',     romaji: ['pinku'],             meaning: 'pink' },
      { kana: 'オレンジ',   romaji: ['orenji'],            meaning: 'orange' },
    ],
  },
  {
    id: 'numbers',
    label: 'Numbers',
    words: [
      { kana: 'いち',       romaji: ['ichi', 'iti'],       meaning: 'one' },
      { kana: 'に',         romaji: ['ni'],                meaning: 'two' },
      { kana: 'さん',       romaji: ['san'],               meaning: 'three' },
      { kana: 'よん',       romaji: ['yon'],               meaning: 'four' },
      { kana: 'ご',         romaji: ['go'],                meaning: 'five' },
      { kana: 'ろく',       romaji: ['roku'],              meaning: 'six' },
      { kana: 'なな',       romaji: ['nana'],              meaning: 'seven' },
      { kana: 'はち',       romaji: ['hachi', 'hati'],     meaning: 'eight' },
      { kana: 'きゅう',     romaji: ['kyuu'],              meaning: 'nine' },
      { kana: 'じゅう',     romaji: ['juu'],               meaning: 'ten' },
    ],
  },
  {
    id: 'time',
    label: 'Time',
    words: [
      { kana: 'きょう',     romaji: ['kyou'],              meaning: 'today' },
      { kana: 'あした',     romaji: ['ashita', 'asita'],   meaning: 'tomorrow' },
      { kana: 'きのう',     romaji: ['kinou'],             meaning: 'yesterday' },
      { kana: 'いま',       romaji: ['ima'],               meaning: 'now' },
      { kana: 'あさ',       romaji: ['asa'],               meaning: 'morning' },
      { kana: 'ひる',       romaji: ['hiru'],              meaning: 'daytime' },
      { kana: 'よる',       romaji: ['yoru'],              meaning: 'night' },
      { kana: 'まいにち',   romaji: ['mainichi', 'mainiti'], meaning: 'every day' },
      { kana: 'らいしゅう', romaji: ['raishuu', 'raisyuu'], meaning: 'next week' },
      { kana: 'せんしゅう', romaji: ['senshuu', 'sensyuu'], meaning: 'last week' },
    ],
  },
  {
    id: 'greetings',
    label: 'Greetings',
    words: [
      { kana: 'はい',         romaji: ['hai'],               meaning: 'yes' },
      { kana: 'いいえ',       romaji: ['iie'],               meaning: 'no' },
      { kana: 'おはよう',     romaji: ['ohayou'],            meaning: 'good morning' },
      { kana: 'こんにちは',   romaji: ['konnichiwa', 'konnitiwa'], meaning: 'hello' },
      { kana: 'こんばんは',   romaji: ['konbanwa'],          meaning: 'good evening' },
      { kana: 'おやすみ',     romaji: ['oyasumi'],           meaning: 'good night' },
      { kana: 'ありがとう',   romaji: ['arigatou'],          meaning: 'thank you' },
      { kana: 'すみません',   romaji: ['sumimasen'],         meaning: 'excuse me' },
      { kana: 'ごめんなさい', romaji: ['gomennasai'],        meaning: 'I\'m sorry' },
      { kana: 'さようなら',   romaji: ['sayounara'],         meaning: 'goodbye' },
    ],
  },
  {
    id: 'nature',
    label: 'Nature',
    words: [
      { kana: 'やま',       romaji: ['yama'],              meaning: 'mountain' },
      { kana: 'かわ',       romaji: ['kawa'],              meaning: 'river' },
      { kana: 'うみ',       romaji: ['umi'],               meaning: 'sea' },
      { kana: 'はな',       romaji: ['hana'],              meaning: 'flower' },
      { kana: 'き',         romaji: ['ki'],                meaning: 'tree' },
      { kana: 'そら',       romaji: ['sora'],              meaning: 'sky' },
      { kana: 'つき',       romaji: ['tsuki', 'tuki'],     meaning: 'moon' },
      { kana: 'ほし',       romaji: ['hoshi', 'hosi'],     meaning: 'star' },
      { kana: 'あめ',       romaji: ['ame'],               meaning: 'rain' },
      { kana: 'ゆき',       romaji: ['yuki'],              meaning: 'snow' },
    ],
  },
];
